version: '3.8'

services:
  squid:
    image: tuiteraz/squid:${LATEST_VERSION}
    container_name: tuiteraz-squid
    user: root
    ports:
      - 5138:5138
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"